### ISSUE TITLE
Wrong SpatialExperiment version loaded from pkgload

### ISSUE THREAD

**Issue by Yifath7** [LieberInstitute/spatialLIBD#12]
When trying to run app.R, I get the following warnings which do not allow me proceed:
 Need SpatialExperiment >= 1.1.5 but loaded version is 1.0.0 
2: object ‘imgData<-’ is not exported by 'namespace:SpatialExperiment' 
3: object ‘spatialCoordsNames<-’ is not exported by 'namespace:SpatialExperiment' 
4: object ‘spatialData<-’ is not exported by 'namespace:SpatialExperiment' 
5: object ‘SpatialImage’ is not exported by 'namespace:SpatialExperiment' 
6: object ‘imgData’ is not exported by 'namespace:SpatialExperiment' 
7: object ‘spatialData’ is not exported by 'namespace:SpatialExperiment' 

Thanks in advance.

**Comment by lcolladotor** [comment]
Hi,

Please post your R session information.

```R
library("sessioninfo")
options(width = 120)
session_info()
```

You most likely are using a combination of Bioconductor 3.13 (current devel) and 3.12 (current release) packages. The GitHub version of `spatialLIBD` is meant to be used with Bioconductor 3.13. https://github.com/LieberInstitute/spatialLIBD/tree/RELEASE_3_12 is 3.12 compatible though.

Best,
Leo

**Comment by Yifath7** [comment]
> Hi,
> 
> Please post your R session information.
> 
> ```r
> library("sessioninfo")
> options(width = 120)
> session_info()
> ```
> 
> You most likely are using a combination of Bioconductor 3.13 (current devel) and 3.12 (current release) packages. The GitHub version of `spatialLIBD` is meant to be used with Bioconductor 3.13. https://github.com/LieberInstitute/spatialLIBD/tree/RELEASE_3_12 is 3.12 compatible though.
> 
> Best,
> Leo

Worked! Thank you :)

Best,
Yifat

**Comment by lcolladotor** [comment]
ok =)
