### ISSUE TITLE
Error when using shiny 1.7.1

### ISSUE THREAD

**Issue by lmweber** [LieberInstitute/spatialLIBD#27]
I am getting the following error when running `spatialLIBD` with the latest version of `shiny` package 1.7.1:

![Screen Shot 2021-11-16 at 14 29 57](https://user-images.githubusercontent.com/8062417/142055630-5f24ff20-a269-4052-8daa-475f9033a4d8.png)

I get this error with the following standard example from the `spatialLIBD` documentation:

```
spe <- fetch_data("spe")
run_app(spe)
```

It works fine with the older version of `shiny` 1.6.0, which I found as a suggestion when googling the error message. I'm not sure why this fixes it though.

Just pasting this issue here for now so we don't lose it.

**Comment by lcolladotor** [comment]
Seems like a duplicate of https://github.com/LieberInstitute/spatialLIBD/issues/24

**Comment by lcolladotor** [comment]
I've pushed all the new changes in `bioc-devel` (3.15) to `bioc-release` (3.14) with https://github.com/LieberInstitute/spatialLIBD/commit/72f60a804c9589ee28809a743c127c0ed0381edd. That includes the fix to #24 and thus this issue.

**Comment by lmweber** [comment]
Ok great, thanks!
