### ISSUE TITLE
Trouble loading two gene sets

### ISSUE THREAD

**Issue by abspangler13** [LieberInstitute/spatialLIBD#39]
I'm having trouble with two of the gene sets. 

The loaded Scatterstrom data doesn't have the correct column names. Here's the code I run and here's the error I get when trying to create `asd_exome_geneList`. 

https://github.com/LieberInstitute/spatialDLPFC/blob/5790c2673cd1661bda7169451f1b75875899fd43/code/analysis/10_Clinical_Gene_Set_Enrichment/01_Clinical_Gene_Set_Enrichment.R#L78-L91

![image](https://user-images.githubusercontent.com/18468963/176024693-2b936266-8f2a-4b35-bcba-f0dc0644ed53.png)

The second gene set doesn't load and I believe it to be a permissions problem. Here is the code I ran to load the data:

https://github.com/LieberInstitute/spatialDLPFC/blob/5790c2673cd1661bda7169451f1b75875899fd43/code/analysis/10_Clinical_Gene_Set_Enrichment/01_Clinical_Gene_Set_Enrichment.R#L172-L175

And here is the error message:

![image](https://user-images.githubusercontent.com/18468963/176025079-be5ab81a-190b-465b-b10e-c9b31b49d788.png)

**Comment by lcolladotor** [comment]
This issue was for this repo https://github.com/LieberInstitute/spatialDLPFC/issues/111 not for `spatialLIBD`. In any case, after our meeting on Thursday, this got resolved.
