### ISSUE TITLE
Use ComplexHeatmap

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/spatialLIBD#54]
Based on the spatialDLPFC project, we decided that the heatmaps look better when made with `ComplexHeatmap`. We need to change all internal heatmaps to use this package.

**Comment by lahuuki** [comment]
![gene_set_enrichment_plot_test](https://github.com/user-attachments/assets/6ecc4fad-402b-4fc0-80c4-c55b6a6942dd)
For gene_set_enrichment plot, do we want to plot the number of genes input with `gene_list` or the number of genes in `modeling_results` in the `gene_list` (reported by `enrichment$SetSize`)? @lcolladotor

**Comment by lahuuki** [comment]
![gene_set_enrichment_plot_test2](https://github.com/user-attachments/assets/464553ac-fcaf-4c51-92de-6674dfa8a725)
Okay I've done both both by implementing the `anno_barplot` so it can show either the `SetSize` or `SetSize` and length of the `gene_lists`

**Comment by lahuuki** [comment]
Work from spatialDLPFC relevant for complex heatmap version of gene_set_enrichment_plot https://github.com/LieberInstitute/spatialDLPFC/blob/main/code/analysis/10_clinical_gene_set_enrichment/gene_set_enrichment_plot_complex.R

**Comment by lcolladotor** [comment]
I think that we can close this one, right? There's just the little detail about colors on `layer_stat_cor_plot()` AFAIK.
